using System.Text.Json.Serialization;

namespace FoundationaLLM.Common.Models.Orchestration.Response
{
    /// <summary>
    /// Represents the result of a function call.
    /// </summary>
    public class FunctionResult
    {
        /// <summary>
        /// The name of the function that was called.
        /// </summary>
        [JsonPropertyName("function_name")]
        public string? FunctionName { get; set; }

        /// <summary>
        /// The inputs provided to the function.
        /// </summary>
        [JsonPropertyName("function_input")]
        public Dictionary<string, string>? FunctionInput { get; set; }

        /// <summary>
        /// The outputs generated by the function.
        /// </summary>
        [JsonPropertyName("function_output")]
        public Dictionary<string, string>? FunctionOutput { get; set; }

        /// <summary>
        /// The category of the agent's capability that was used in the function call.
        /// </summary>
        [JsonPropertyName("agent_capability_category")]
        public string? AgentCapabilityCategory { get; set; }
    }
}
