using FoundationaLLM.Common.Constants.ResourceProviders;
using FoundationaLLM.Common.Exceptions;
using System.Text.Json.Serialization;

namespace FoundationaLLM.Common.Models.ResourceProviders.Attachment
{
    /// <summary>
    /// Contains a reference to an attachment.
    /// </summary>
    public class AttachmentReference : ResourceReference
    {
        /// <summary>
        /// The original file name of the attachment.
        /// This is useful because the resource name is generated by the system
        /// and may not be the same as the original file name.
        /// </summary>
        public string OriginalFilename { get; set; } = string.Empty;

        /// <summary>
        /// The mime content type of the attachment.
        /// </summary>
        public string ContentType { get; set; } = string.Empty;

        /// <summary>
        /// The size of the file.
        /// </summary>
        public long Size { get; set; }

        /// <summary>
        /// Indicates an optional secondary provider for the attachment.
        /// </summary>
        /// <remarks>
        /// The only secondary provider currently supported is the FoundationaLLM.AzureOpenAI provider.
        /// </remarks>
        public string? SecondaryProvider { get; set; }

        /// <summary>
        /// Gets or sets the object identifier of the secondary provider of the attachment.
        /// </summary>
        /// <remarks>
        /// The only secondary provider currently supported is FoundationaLLM.AzureOpenAI.
        /// In this case, the object identifier is the Azure OpenAI file identifier.
        /// </remarks>
        public string? SecondaryProviderObjectId { get; set; }

        /// <summary>
        /// The UPN of the user who created the attachment.
        /// </summary>
        [JsonPropertyName("upn")]
        public string UPN { get; set; } = string.Empty;

        /// <summary>
        /// The unique identifier.
        /// </summary>
        [JsonPropertyName("id")]
        public required string Id { get; set; }

        /// <summary>
        /// The object type of the resource.
        /// </summary>
        [JsonIgnore]
        [Newtonsoft.Json.JsonIgnore]
        public override Type ResourceType =>
            Type switch
            {
                AttachmentTypes.File => typeof(AttachmentFile),
                AttachmentTypes.AgentPrivateFile => typeof(AgentPrivateFile),
                _ => throw new ResourceProviderException($"The resource type {Type} is not supported.")
            };
    }
}
