import PrimeVue from 'primevue/config';
import AutoComplete from 'primevue/autocomplete';
import Button from 'primevue/button';
import Calendar from 'primevue/calendar';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Dialog from 'primevue/dialog';
import Toast from 'primevue/toast';
import Card from 'primevue/card';
import Chip from 'primevue/chip';
import Chips from 'primevue/chips';
import ToastService from 'primevue/toastservice';
import Tooltip from 'primevue/tooltip';
import Divider from 'primevue/divider';
import Dropdown from 'primevue/dropdown';
import MultiSelect from 'primevue/multiselect';
import Avatar from 'primevue/avatar';
import RadioButton from 'primevue/radiobutton';
import ToggleButton from 'primevue/togglebutton';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import FileUpload from 'primevue/fileupload';
import Badge from 'primevue/badge';
import BadgeDirective from 'primevue/badgedirective';
import ProgressBar from 'primevue/progressbar';
import ColorPicker from 'primevue/colorpicker';
import InputSwitch from 'primevue/inputswitch';
import InputNumber from 'primevue/inputnumber';
import TabView from 'primevue/tabview';
import TabPanel from 'primevue/tabpanel';

import { defineNuxtPlugin } from '#app';

export default defineNuxtPlugin((nuxtApp) => {
	nuxtApp.vueApp.use(PrimeVue, { ripple: true });
	nuxtApp.vueApp.component('AutoComplete', AutoComplete);
	nuxtApp.vueApp.component('Button', Button);
	nuxtApp.vueApp.component('Calendar', Calendar);
	nuxtApp.vueApp.component('InputText', InputText);
	nuxtApp.vueApp.component('Textarea', Textarea);
	nuxtApp.vueApp.component('Dialog', Dialog);
	nuxtApp.vueApp.component('Toast', Toast);
	nuxtApp.vueApp.component('Card', Card);
	nuxtApp.vueApp.component('Chip', Chip);
	nuxtApp.vueApp.component('Chips', Chips);
	nuxtApp.vueApp.component('Divider', Divider);
	nuxtApp.vueApp.component('Dropdown', Dropdown);
	nuxtApp.vueApp.component('MultiSelect', MultiSelect);
	nuxtApp.vueApp.component('Avatar', Avatar);
	nuxtApp.vueApp.component('RadioButton', RadioButton);
	nuxtApp.vueApp.component('ToggleButton', ToggleButton);
	nuxtApp.vueApp.component('DataTable', DataTable);
	nuxtApp.vueApp.component('Column', Column);
	nuxtApp.vueApp.component('FileUpload', FileUpload);
	nuxtApp.vueApp.component('Badge', Badge);
	nuxtApp.vueApp.directive('badge', BadgeDirective);
	nuxtApp.vueApp.component('ProgressBar', ProgressBar);
	nuxtApp.vueApp.component('ColorPicker', ColorPicker);
	nuxtApp.vueApp.component('InputSwitch', InputSwitch);
	nuxtApp.vueApp.component('InputNumber', InputNumber);
	nuxtApp.vueApp.component('TabView', TabView);
	nuxtApp.vueApp.component('TabPanel', TabPanel);

	nuxtApp.vueApp.use(ToastService);
});
