using System.Text.Json.Serialization;

namespace FoundationaLLM.Common.Models.ResourceProviders
{
    /// <summary>
    /// Contains a reference to a file.
    /// </summary>
    public class FileReference : ResourceReference
    {
        /// <summary>
        /// The original file name of the file.
        /// This is useful because the resource name is generated by the system
        /// and may not be the same as the original file name.
        /// </summary>
        public string OriginalFilename { get; set; } = string.Empty;

        /// <summary>
        /// The mime content type of the file.
        /// </summary>
        public string ContentType { get; set; } = string.Empty;

        /// <summary>
        /// The size of the file.
        /// </summary>
        public long Size { get; set; }

        /// <summary>
        /// The UPN of the user who created the file.
        /// </summary>
        [JsonPropertyName("upn")]
        public string UPN { get; set; } = string.Empty;

        /// <summary>
        /// The unique identifier.
        /// </summary>
        [JsonPropertyName("id")]
        public required string Id { get; set; }
    }
}
